apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  BACKEND_URL: http://todo-backend:8000
  NODE_ENV: production
  PYTHON_ENV: production
