apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.frontendLabels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "todo-app.frontendSelectorLabels" . | nindent 6 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: 3000
      nodePort: {{ .Values.frontend.nodePort }}
      protocol: TCP
